### ISSUE TITLE
PB help? global search

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/jire2#254]
@johnsisland 

We're beyond frustrated with Anthony explaining or trying to help us understand why PB Global Search doesn't behave the way we expect it to.

For example, search for "Horan".

They are a current listing at 850 Beach Road #375 and the current owner! The global search should be showing us their CONTACT, LISTING and PROPERTY records, but it doesn't. Why isn't PB finding any match with Horan in the field? 

Ironically, in the example above, it will pull a 600 Beach Road #241 PROPERTY that is linked to a past owner. It's almost like it finds "Horan" in any other field, but the PROPERTY OWNER field, etc. We've been very disappointed with the varying results. Seems to work one day, then not the next. He just "fixed" something to help with this problem, but now the PROPERTY record doesn't appear in the results.

**Comment by CodySwannGT** [comment]
@johnsisland is this still worth keeping open?

**Comment by johnsisland** [comment]
Let's close it. I'm sure I'll hear more from the team this summer when things slow down.
