### ISSUE TITLE
Home Page: Portfolio Latest Issue not updating with new image or link/content

### ISSUE THREAD

**Issue by johnsisland** [gunnertech/jire2#272]
Hi Cody, This is the 2nd time where I've updated the Home Page's Portfolio content in Refinery with new images, content and links, but the front end doesn't refresh/change. The Refinery link below showing the new content.  If it doesn't refresh for me, is it not refreshing for our clients as well? 

http://www.johnsislandrealestate.com/refinery/pages/home/portfolio-latest-issue/edit

**Comment by CodySwannGT** [comment]
The cache should automatically flush now
